package it.polimi.ingsw.enums;

public enum State {
    /*CLIENT to SERVER*/
    SET_NICKNAME,
    SET_NUMPLAYERS,
    SELECT_ITEM,
    CONFIRM_ITEMS,
    ORDER_ITEM,
    DISORDER_ITEM,
    SELECT_COLUMN,
    CONFIRM_INSERTION,

    /*SERVER to CLIENT*/
    ACK_NICKNAME,
    ASK_NUMPLAYERS,
    SAME_NICKNAME,
    NACK_NICKNAME,
    ACK_NUMPLAYERS,
    OUT_BOUND_NUMPLAYERS,
    SEND_MODEL,
    SELECTED,
    ORDER_n_COLUMN
}
