package it.polimi.ingsw.enums;

public enum State {
    SET_NICKNAME,
    SET_NUMPLAYERS,
    SELECT_ITEM,
    DESELECT_CELL,
    CONFIRM_ITEMS,
    ORDER_ITEM,
    DISORDER_ITEM,
    SELECT_COLUMN,
    CONFIRM_INSERTION,
    ACK_NICKNAME,
    ASK_NUMPLAYERS,
    SAME_NICKNAME,
    NACK_NICKNAME,
    ACK_NUMPLAYERS,
    OUT_BOUND_NUMPLAYERS,
    SEND_MODEL
}
